# Generated by Django 5.2 on 2025-06-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layananhotel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='name_customer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='-', max_length=15),
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
