# Generated by Django 5.2 on 2025-06-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layananhotel_app', '0002_remove_booking_guest_remove_booking_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_cashier',
            field=models.BooleanField(default=False),
        ),
    ]
