# Generated by Django 5.2 on 2025-07-22 10:55

import layananhotel_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layananhotel_app', '0004_payment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='code',
            field=models.CharField(default=layananhotel_app.models.increment_booking_code, editable=False, max_length=20),
        ),
    ]
